import { Product } from './types';

export const CATEGORIES = [
  { id: 'all', name: 'ທັງໝົດ', icon: 'LayoutGrid' },
  { id: 'electronics', name: 'ອີເລັກໂທຣນິກ', icon: 'Smartphone' },
  { id: 'fashion', name: 'ເສື້ອຜ້າ & แຟຊັ່ນ', icon: 'Shirt' },
  { id: 'cosmetics', name: 'ຄວາມງາມ & ສະກິນແຄຣ໌', icon: 'Sparkles' },
  { id: 'home', name: 'ເຄື່ອງໃຊ້ໃນເຮືອນ', icon: 'Home' },
  { id: 'sports', name: 'ອຸປະກອນກິລາ', icon: 'Dumbbell' }
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'ໂທລະສັບ Galaxy S24 Ultra (512GB)',
    price: 29500000,
    originalPrice: 42000000,
    category: 'electronics',
    brand: 'Samsung',
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=600&auto=format&fit=crop',
    badge: 'ຫຼຸດພິເສດ 30%',
    countSold: 'ຂາຍແລ້ວ 240+ ຊິ້ນ',
    description: 'ໂທລະສັບສະມາດໂຟນລຸ້ນທັອບພ້ອມລະບົບ AI ທັນສະໄໝ, ກ້ອງຖ່າຍຮູບຄວາມລະອຽດ 200MP, ແລະ ປາກກາ S-Pen ໃນຕົວ.',
    options: 'Color: Titanium Gray, Titanium Black, Titanium Yellow'
  },
  {
    id: 'p2',
    name: 'ຫູຟັງໄຮ້ສາຍ Headphones Wireless Pro 2024',
    price: 2450000,
    originalPrice: 3800000,
    category: 'electronics',
    brand: 'Sony',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDYY-QUvyKEfA3FUJI9MFgySFHZjozAMX7XK_4jXujttr047rSRuzUCzGuY_6yaWLib8PGm_zndKd8JMiiVrnTIB-_bB6wFE8AiJ4_jSJtZyx_tqE89JqO75hcXtF4npI897UsnGrJhbzVyeEG1b6VcLLJWjwFTEqpWYBgi-mRlatq7gtRUe2tp2qGt_UdagAQAssmCn1WQvE6CPvCWkobwFM2WDOjFWPNvWVg3Ctgz3VSz1xvnpI9Nd46AObjluYEmWw4lG_5qXic',
    badge: 'ຍອດນિຍົມ',
    countSold: 'ຂາຍແລ້ວ 890+ ຊິ້ນ',
    description: 'ຫູຟັງຄອບຫູຕັດສຽງລົບກວນອັດສະລິຍະ (ANC) ໃຫ້ພະລັງສຽງເບສທີ່ແໜ້ນໜາ ແລະ ຊັດເຈນ ໃຊ້ງານໄດ້ຍາວນານເຖິງ 30 ຊົ່ວໂມງ.',
    options: 'Color: Pearl Black, Ivory White'
  },
  {
    id: 'p3',
    name: 'ໂມງອັດສະລິຍະ Smart Watch Classic Edition',
    price: 1850000,
    originalPrice: 2900000,
    category: 'electronics',
    brand: 'Apple',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBnsNnCvNtIeH1kQhkuTnFklIpr_TkotZe3FGrl_kvHcw-B3auzjPiHqgCe7kYqSKXH6dpmWJv_VjSISa2K6ehST2mOwxBQRrqfPPZYwpt5tT5i6QBi1kTJInQNCn_uKQ7EEhPsT6k3ocMViGmOHGWwUDJQ_X1iSWwYBC553yPPeAVm_vHxQfh77Sxcz0FWrLy_z1sSi3wdm6gzCZrfTJ9PAX3bYBfHyILsI8oL9BjCvNgSAswjWPFetFoX5heOcV0pQMg3G27AnuU',
    badge: 'ຫຼຸດແຮງ!! 35%',
    countSold: 'ຂາຍແລ້ວ 420+ ຊິ້ນ',
    description: 'ຕິດຕາມສຸຂະພາບຂອງທ່ານຕະຫຼອດ 24 ຊົ່ວໂມງ, ວັດແທກອັດຕາການເຕັ້ນຂອງຫົວໃຈ, ການນອນ, ແລະ ຮອງຮັບການອອກກຳລັງກາຍຫຼາຍຮູບແບບ.',
    options: 'Strap: Sport Black, Classic Leather Brown'
  },
  {
    id: 'p4',
    name: 'ເກີບກິລາ Comfort Plus Sneaker',
    price: 1350000,
    originalPrice: 2400000,
    category: 'fashion',
    brand: 'SportX',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAFMC9UFGKg3Hkx7HhLKH4kZ7VCIdI8LELrVnV337_vU_lrxE4uRxrHSPKwPe-vBmMtjRMN3FCKU3MscU3upFDb2IOkxYqdnVSEzPCrL153TQBkbWIMB_8N_StkhuY_Mi2l8jYe_ItDp8BemplBokQ9hEW3_f5eHwC77CI17AkDYiPlIs5j5SuFitVIG7I5kr7n6mtD_QfeG2T4m65g9aZsLxfHXjhmK6kJn_37SvzWySLmpIkmmCyN4w8D6jTfbQWZj0PeOXcW-Uo',
    badge: 'ຂາຍດີ',
    countSold: 'ຂາຍແລ້ວ 1.2k+ ຊິ້ນ',
    description: 'ເກີບວິ່ງແລະອອກກຳລັງກາຍທີ່ມີເທັກໂນໂລຢີນ້ຳໜັກເບົາ, ຊ່ວຍຮັບແຮງກະແທກໄດ້ດີ ແລະ ລະບາຍອາກາດໄດ້ດີເລີດ.',
    options: 'Size: 39, 40, 41, 42, 43, 44'
  },
  {
    id: 'p5',
    name: 'ເສື້ອກັນໜາວ Activewear Flex Jacket',
    price: 650000,
    originalPrice: 950000,
    category: 'fashion',
    brand: 'Apex',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC032VSuHQiDRgAvSvuCSqIPuvUQfXhtf_lkKuclBpiRcE5wwEfmSjCVhKKDcapWkoLYCx_xUTkfAbzadphsLxdUZ81dw8oxrL4-damx4CBbzXbYUB0oQ_UikKgpNEgqqgNrcf0MGzRZXkZcaoGDIbfyh3LcGyRiulGMx537x3-eOMEe8HKQZeCLtmFp8ab4-W0LTaT03rlDbzh3aUM54Pkfg9UbtN96LCGa3r7_-1H6wylMERQ00ZVJVvbSlR2E5Uz9R8PySwsZtI',
    badge: 'ຫຼຸດ 30%',
    countSold: 'ຂາຍແລ້ວ 310+ ຊິ້ນ',
    description: 'ເສື້ອກັນໜາວອອກກຳລັງກາຍ ຜ້າຢືດຢຸ່ນສູງ ກັນລົມແລະລະບາຍເຫື່ອໄດ້ດີ, ເໝາະສຳລັບທັງການອອກກຳລັງກາຍ ແລະ ໃສ່ທົ່ວໄປ.',
    options: 'Size: M, L, XL, XXL'
  },
  {
    id: 'p6',
    name: 'ເຊລັ່ມບຳລຸງຜິວໜ້າ Organic Face Serum 50ml',
    price: 490000,
    originalPrice: 850000,
    category: 'cosmetics',
    brand: 'NaturaLao',
    image: 'https://images.unsplash.com/photo-1608248597481-496100c80836?q=80&w=600&auto=format&fit=crop',
    badge: 'ຫຼຸດພิເສດ 42%',
    countSold: 'ຂາຍແລ້ວ 1.5k+ ຊິ້ນ',
    description: 'ເຊລັ່ມສະກັດຈາກທຳມະຊາດ 100% ຊ່ວຍຟື້ນຟູຜິວໜ້າໃຫ້ຂາວໃສ ອີ່ມນ້ຳ ຫຼຸດຮອຍດຳ ແລະ ກະຊັບຮູຂຸມຂົນເປັນຢ່າງດີ.',
    options: 'Skin Type: All Skin Types'
  },
  {
    id: 'p7',
    name: 'ລຳໂພງບູທູດ Portable Speaker V5',
    price: 890000,
    originalPrice: 1500000,
    category: 'electronics',
    brand: 'JBL',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA4tqzg_yIJHN7ldFRxuBl6q-p-ygm8dttiC7_b8t6XbXx3PY8Cjx3RtAPTGeDvr_o3jlyREFtYktJXI4VWeNMwsBE7sTmkGq8GR39BBrFBNgc9RocA4uZnzF3uxUvUvmqyYlTXj-OK_pF1Gqr1fcUStQdzCXA2l-FgVTQ5zVeBGGWt3SsjzYuekuMQlHtbe2TABW29LD5DjTpQqr71GRWWIYI4pusq84gU8cIDFZF5Bk4fcxKgvX4dKHRV2nXNkAxKO1NfpwZSXVs',
    badge: 'ຫຼຸດ 40%',
    countSold: 'ຂາຍແລ້ວ 520+ ຊິ້ນ',
    description: 'ລຳໂພງພົກພາແບບກັນນ້ຳ ມາດຕະຖານ IPX7 ໃຫ້ສຽງເບສໜັກແໜ້ນເໝາະກັບການໄປທ່ຽວປ່າ ຫຼື ຈັດງານປາຕີ້.',
    options: 'Color: Forest Green, Ocean Blue, Stealth Black'
  },
  {
    id: 'p8',
    name: 'ຄີມບຳລຸງກັນແດດ Sunscreen UV Shield SPF50+',
    price: 290000,
    originalPrice: 420005,
    category: 'cosmetics',
    brand: 'NaturaLao',
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=600&auto=format&fit=crop',
    badge: 'ຫຼຸດພິເສດ 30%',
    countSold: 'ຂາຍແລ້ວ 2k+ ຊິ້ນ',
    description: 'ຄີມກັນແດດສູດນ້ຳ ບາງເບົາ ບໍ່ໜຽວເນິະໜະ ປົກປ້ອງຜິວຈາກລັງສີ UVA ແລະ UVB ໄດ້ຕະຫຼອດທັງວັນ.',
    options: 'Size: 30ml, 50ml'
  },
  {
    id: 'p9',
    name: 'ເຄື່ອງຕົ້ມກາເຟ Espresso Coffee Machine',
    price: 3600000,
    originalPrice: 5800000,
    category: 'home',
    brand: 'DeLonghi',
    image: 'https://images.unsplash.com/photo-1517256064527-09c53b2d0bc6?q=80&w=600&auto=format&fit=crop',
    badge: 'ຫຼຸດພິເສດ 37%',
    countSold: 'ຂາຍແລ້ວ 110+ ຊິ້ນ',
    description: 'ເຄື່ອງຕົ້ມກາເຟເອສເປຼດໂຊ້ລະບົບອັດຕະໂນມັດ ຄວາມດັນ 15 ບາ, ສາມາດຕີຟອງນົມໄດ້ໜານຸ່ມ ເໝາະສຳລັບເຮືອນ ແລະ ຫ້ອງການ.',
    options: 'Voltage: 220V standard'
  },
  {
    id: 'p10',
    name: 'ໂຄມໄຟຫົວຕຽງອັດສະລິຍະ LED Smart Table Lamp',
    price: 390000,
    originalPrice: 750000,
    category: 'home',
    brand: 'Xiaomi',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=600&auto=format&fit=crop',
    badge: 'ຫຼຸດແຮງ!! 48%',
    countSold: 'ຂາຍແລ້ວ 340+ ຊິ້ນ',
    description: 'ໂຄມໄຟປັບປ່ຽນສີໄດ້ 16 ລ້ានສີ ຮອງຮັບການສັ່ງວຽນດ້ວຍສຽງ ແລະ ສາມາດຄວບຄຸມຜ່ານແອັບພລິເຄຊັນເທິງມືຖື.',
    options: 'Power: USB Plug-in'
  },
  {
    id: 'p11',
    name: 'ກະເປົາເປ້ເດີນທາງ Leather Travel Backpack',
    price: 890000,
    originalPrice: 1250000,
    category: 'fashion',
    brand: 'VintageLao',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=600&auto=format&fit=crop',
    badge: 'ຫຼຸດ 28%',
    countSold: 'ຂາຍແລ້ວ 280+ ຊິ້ນ',
    description: 'ກະເປົາເປ້ໜັງແທ້ດີໄຊນ໌ຄລາສສິກ ມີຄວາມທົນທານສູງ ສາມາດບັນຈຸໂນດບຸກຂະໜາດ 15 ນິ້ວ ແລະ ສິ່ງຂອງເດີນທາງໄດ້ຢ່າງສະບາຍ.',
    options: 'Color: Cocoa Brown, Matte Black'
  },
  {
    id: 'p12',
    name: 'ແວ່ນຕາກັນແດດແຟຊັ່ນ Classic Sunglasses',
    price: 220000,
    originalPrice: 500000,
    category: 'fashion',
    brand: 'RayBan',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=600&auto=format&fit=crop',
    badge: 'ຫຼຸດແຮງ!! 56%',
    countSold: 'ຂາຍແລ້ວ 670+ ຊິ້ນ',
    description: 'ແວ່ນຕາກັນແດດປ້ອງກັນ UV400 ກອບໂລຫະແຂງແຮງນ້ຳໜັກເບົາ ເໝາະກັບທຸກຮູບທົງໃບໜ້າຂອງທັງຍິງແລະຊາຍ.',
    options: 'Lens: Polarized Black, Gold Mirror'
  },
  {
    id: 'p13',
    name: 'ຊຸດດຳເບລປັບນ້ຳໜັກ Chrome Dumbbell Set (20kg)',
    price: 980000,
    originalPrice: 1600000,
    category: 'sports',
    brand: 'SportX',
    image: 'https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?q=80&w=600&auto=format&fit=crop',
    badge: 'ຫຼຸດ 38%',
    countSold: 'ຂາຍແລ້ວ 180+ ຊິ້ນ',
    description: 'ຊຸດດຳເບລປັບນ້ຳໜັກໄດ້ 20 ກິໂລກຣາມ ວັດສະດຸເຫຼັກຊຸບໂຄຣມຽມຢ່າງດີ ພ້ອມກ່ອງຈັດເກັບແຂງແຮງ ພົກພາງ່າຍ ສະດວກໃນການອອກກຳລັງກາຍຢູ່ເຮືອນ.',
    options: 'Weight: 20kg Set, 30kg Set'
  },
  {
    id: 'p14',
    name: 'ເສື່ອໂຢຄະ TPE Premium Non-Slip Mat (6mm)',
    price: 270000,
    originalPrice: 450000,
    category: 'sports',
    brand: 'Apex',
    image: 'https://images.unsplash.com/photo-1592432678016-e910b452f9a2?q=80&w=600&auto=format&fit=crop',
    badge: 'ຫຼຸດ 40%',
    countSold: 'ຂາຍແລ້ວ 350+ ຊິ້ນ',
    description: 'ເສື່ອໂຢຄະຜະລິດຈາກວັດສະດຸ TPE ຄຸນນະພາບສູງ ເປັນມິດຕໍ່ສິ່ງແວດລ້ອມ ຄວາມໜາ 6 ມມ ປ້ອງກັນການມື່ນ ແລະ ຮອງຮັບແຮງກະແທກໄດ້ດີເລີດ, ກັນນ້ຳ ແລະ ທຳຄວາມສະອາດງ່າຍ.',
    options: 'Color: Forest Green, Pink Pastel, Ocean Blue'
  },
  {
    id: 'p15',
    name: 'ชຸດໄມ້ຕີແບັດມິນຕັນຄູ່ Carbon Fibre Rackets',
    price: 540000,
    originalPrice: 900000,
    category: 'sports',
    brand: 'Apex',
    image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?q=80&w=600&auto=format&fit=crop',
    badge: 'ຫຼຸດ 40%',
    countSold: 'ຂາຍແລ້ວ 120+ ຊິ້ນ',
    description: 'ຊຸດໄມ້ຕີແບັດມິນຕັນຄູ່ ຜະລິດຈາກຄາບອນໄຟເບີນ້ຳໜັກເບົາ ແຂງແຮງ ພ້ອມກະເປົາພົກພາ ແລະ ລູກຂົນໄກ່ 3 ລູກ ພ້ອມຫຼິ້ນ.',
    options: 'Color: Neon Yellow, Fire Red'
  },
  {
    id: 'p16',
    name: 'ໝາກບານບ້ວງໜັງແທ້ Basketball Pro Leather No.7',
    price: 480000,
    originalPrice: 800000,
    category: 'sports',
    brand: 'SportX',
    image: 'https://images.unsplash.com/photo-1519766304817-4f37bda74a27?q=80&w=600&auto=format&fit=crop',
    badge: 'ຫຼຸດ 40%',
    countSold: 'ຂາຍແລ້ວ 95+ ຊິ້ນ',
    description: 'ໝາກບານບ້ວງໜັງແທ້ເບີ 7 ຈັບກະຊັບມື ປ້ອງກັນການມື່ນຊຸ່ມເຫື່ອ ທົນທານຕໍ່ການໃຊ້ງານທັງໃນຮົ່ມ ແລະ ກາງແຈ້ງ ມາດຕະຖານການແຂ່ງຂັນ.',
    options: 'Size: Official Size 7'
  },
  {
    id: 'p17',
    name: 'ຊຸດຄັນເບັດຕົກປາຄົບເຊັດ Fishing Rod Full Combo Set',
    price: 290000,
    originalPrice: 420000,
    category: 'sports',
    brand: 'Daiwa',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=600&auto=format&fit=crop',
    badge: 'ຫຼຸດ 31%',
    countSold: 'ຂາຍແລ້ວ 240+ ຊິ້ນ',
    description: 'ຊຸດຄັນເບັດຕົກປາຄົບເຊັດສຸດຄຸ້ມເຄິ່ງລາຄາ! ປະກອບດ້ວຍ ຄັນເບັດໄຟເບີກລາສຍາວ 1.8 ແມັດ ລໍ້ສະປິນນິງແຂງແກ່ນ, ສາຍ PE ຖັກ 8 (100m) ແລະ ແຖມຟຣີເຫຍື້ອປອມກົບຢາງ 1 ໂຕ ພ້ອມໃຊ້ງານທັນທີ.',
    options: 'ຄັນເບັດ: 1.8m + ລໍ້ສະປິນ, 2.1m + ລໍ້ສະປິນ'
  },
  {
    id: 'p18',
    name: 'ເຫຍື້ອປອມກົບຢາງລະດັບພຣີມ່ຽມ Silicon Rubber Frog Lures (3 ຊຸດ)',
    price: 35000,
    originalPrice: 65000,
    category: 'sports',
    brand: 'LurePro',
    image: 'https://images.unsplash.com/photo-1605647540924-852290f6b0d5?q=80&w=600&auto=format&fit=crop',
    badge: 'ຫຼຸດ 46%',
    countSold: 'ຂາຍແລ້ວ 410+ ຊິ້ນ',
    description: 'ເຫຍື້ອປອມກົບຢາງສຳລັບຕົກປາຊັ້ນດີ ຜະລິດຈາກຊິລິໂຄນໜຽວທົນທານພິເສດ ບໍ່ຂາດງ່າຍ, ແອັກຊັ້ນສ້າງຄື້ນນ້ຳດຶງດູດປາລ່າເຫຍື້ອສະເພາະຕົວ ເໝາະກັບປາຊອນ, ປາໂດ.',
    options: 'Color: Green Neon, Cute Orange, Pink Panther'
  },
  // ADDING 20 NEW ITEMS (p19 to p38) Across all categories to fully expand and populate the shop with cheaper prices!
  {
    id: 'p19',
    name: 'ພັດລົມໄຟຟ້າຂະໜາດນ້ອຍ Mini USB Desk Fan',
    price: 75000,
    originalPrice: 110000,
    category: 'home',
    brand: 'Xiaomi',
    image: 'https://images.unsplash.com/photo-1618945041113-4811f5068f00?q=80&w=600&auto=format&fit=crop',
    badge: 'ເຄື່ອງໃຊ້ໃນເຮືອນ',
    countSold: 'ຂາຍແລ້ວ 430+ ຊິ້ນ',
    description: 'ພັດລົມຕັ້ງໂຕະໄຟຟ້າຂະໜາດນ້ອຍ ສາກໄຟຜ່ານ USB ສຽງງຽບ ປັບແຮງລົມໄດ້ 3 ລະດັບ ຕັ້ງໃຊ້ງານສະດວກທຸກບ່ອນ.',
    options: 'Color: Mint Green, Cozy White'
  },
  {
    id: 'p20',
    name: 'ໝໍ້ຫຸງເຂົ້າໄຟຟ້າອັດສະລິຍະ Smart Rice Cooker 1.5L',
    price: 395000,
    originalPrice: 580000,
    category: 'home',
    brand: 'Xiaomi',
    image: 'https://images.unsplash.com/photo-1544237515-385a7cdd8b91?q=80&w=600&auto=format&fit=crop',
    badge: 'ສິນຄ້າຂາຍດີ 🌟',
    countSold: 'ຂາຍແລ້ວ 150+ ຊິ້ນ',
    description: 'ໝໍ້ຫຸງເຂົ້າລະບົບດິຈິຕອນ ຄວາມຈຸ 1.5 ລິດ ຫຸງເຂົ້າໜຽວ ເຂົ້າຈ້າວ ຫຼື ເຮັດແກງກໍສະດວກ ຄວບຄຸມອຸນຫະພູມໄດ້ຢ່າງຊັດເຈນ.',
    options: 'Type: 1.5L Digital'
  },
  {
    id: 'p21',
    name: 'ກະຕິກນ້ຳຮ້ອນໄຟຟ້າ Stainless Steel Kettle 1.8L',
    price: 135000,
    originalPrice: 195000,
    category: 'home',
    brand: 'Apex',
    image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?q=80&w=600&auto=format&fit=crop',
    badge: 'ຄຸ້ມຄ່າ',
    countSold: 'ຂາຍແລ້ວ 720+ ຊິ້ນ',
    description: 'ກະຕິກນ້ຳຮ້ອນສະແຕນເລດ ຕົ້ມນ້ຳຟົດໄວພາຍໃນ 2 ນາທີ ມີລະບົບຕັດໄຟອັດຕະໂນມັດເມື່ອນ້ຳຟົດ ປອດໄພທົນທານ.',
    options: 'Capacity: 1.8L'
  },
  {
    id: 'p22',
    name: 'ເຄື່ອງປັ່ນນ້ຳໝາກໄມ້ພົກພາ Portable USB Blender',
    price: 190000,
    originalPrice: 280000,
    category: 'home',
    brand: 'FreshPro',
    image: 'https://images.unsplash.com/photo-1578643463396-0997cb5328c1?q=80&w=600&auto=format&fit=crop',
    badge: 'ຮ້ອນແຮງ 🔥',
    countSold: 'ຂາຍແລ້ວ 550+ ຊິ້ນ',
    description: 'ເຄື່ອງປັ່ນໝາກໄມ້ຂະໜາດພົກພາ ສາກໄຟ USB ໃບມີດສະແຕນເລດ 6 ແສກ ປັ່ນນ້ຳກ້ອນ ແລະ ໝາກໄມ້ໄດ້ລະອຽດໄວທັນໃຈ.',
    options: 'Color: Pastel Pink, Ice Blue'
  },
  {
    id: 'p23',
    name: 'ໝໍ້ຂົ້ວກະລິ່ນບໍ່ຕິດກະທະ Non-Stick Frying Pan (24cm)',
    price: 110000,
    originalPrice: 175000,
    category: 'home',
    brand: 'ChefClassic',
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?q=80&w=600&auto=format&fit=crop',
    badge: 'ຫຼຸດພິເສດ',
    countSold: 'ຂາຍແລ້ວ 480+ ຊິ້ນ',
    description: 'ກະທະເຄືອບຫີນອ່ອນ ທົນທານ ບໍ່ຕິດກະທະ ໃຊ້ນ້ຳມັນໜ້ອຍ ປອດໄພຕໍ່ດຸ່ນສຸຂະພາບ ອົບຄວາມຮ້ອນໄດ້ທົ່ວເຖິງ.',
    options: 'Size: 24cm Ceramic Coating'
  },
  {
    id: 'p24',
    name: 'ພາວເວີແບງ Fast Charge Power Bank 30,000mAh',
    price: 185000,
    originalPrice: 270000,
    category: 'electronics',
    brand: 'Anker',
    image: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b17c?q=80&w=600&auto=format&fit=crop',
    badge: 'ມາໃໝ່',
    countSold: 'ຂາຍແລ້ວ 890+ ຊິ້ນ',
    description: 'ແບັດເຕີຣີສຳຮອງຄວາມຈຸສູງ 30,000mAh ຮອງຮັບລະບົບສາກໄວ QC 3.0 ແລະ PD Type-C ສາກໄດ້ຫຼາຍອຸປະກອນພ້ອມກັນ.',
    options: 'Color: Matte Black, Pearl White'
  },
  {
    id: 'p25',
    name: 'ເມົາສ໌ເກມມິ່ງໄຮ້ສາຍ Ergonomic Wireless Mouse',
    price: 120000,
    originalPrice: 195000,
    category: 'electronics',
    brand: 'Logitech',
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?q=80&w=600&auto=format&fit=crop',
    badge: 'ແນະນຳ',
    countSold: 'ຂາຍແລ້ວ 350+ ຊິ້ນ',
    description: 'ເມົາສ໌ໄຮ້ສາຍດີໄຊນ໌ຮັບກັບຮູບມື ຫຼຸດຜ່ອນຄວາມເມື່ອຍລ້າ ປັບແຮງ DPI ໄດ້ 4 ລະດັບ ຕອບສະໜອງໄວ ບໍ່ມີສະດຸດ.',
    options: 'Color: Charcoal Gray, Cute Pink'
  },
  {
    id: 'p26',
    name: 'ຄີບອດເມຄານິຄໍ Mechanical RGB Keyboard Pro',
    price: 490000,
    originalPrice: 750000,
    category: 'electronics',
    brand: 'Keychron',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=600&auto=format&fit=crop',
    badge: 'ຂາຍດີ',
    countSold: 'ຂາຍແລ້ວ 190+ ຊິ້ນ',
    description: 'ຄີບອດຄຸນນະພາບສູງ ສຳລັບນັກຂຽນໂປຣແກຣມ ແລະ ເກມເມີ້, ປຸ່ມ Blue Switch ກົດມ່ວນມື ພ້ອມໄຟ LED RGB ປ່ຽນຮູບແບບໄດ້.',
    options: 'Switch: Blue Switch, Red Switch'
  },
  {
    id: 'p27',
    name: 'ກ້ອງວົງຈອນປິດໄຮ້ສາຍ Smart IP Camera 2K',
    price: 320000,
    originalPrice: 480000,
    category: 'electronics',
    brand: 'Xiaomi',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=600&auto=format&fit=crop',
    badge: 'ປ້ອງກັນໄພ',
    countSold: 'ຂາຍແລ້ວ 540+ ຊິ້ນ',
    description: 'ກ້ອງວົງຈອນປິດຄວາມລະອຽດສູງ 2K ເບິ່ງພາບຜ່ານມືຖືໄດ້ 360 ອົງສາ ມີລະບົບຈັບພາບເຄື່ອນໄຫວ ແລະ Night Vision ໃນບ່ອນມືດ.',
    options: 'Storage: Support MicroSD card up to 256GB'
  },
  {
    id: 'p28',
    name: 'ເສື້ອຢືດຝ້າຍແທ້ Premium Cotton Oversized Tee',
    price: 85000,
    originalPrice: 140000,
    category: 'fashion',
    brand: 'VintageLao',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=600&auto=format&fit=crop',
    badge: 'ເສື້ອຜ້າແຟຊັ່ນ',
    countSold: 'ຂາຍແລ້ວ 1.1k+ ຊິ້ນ',
    description: 'ເສື້ອຢືດຝ້າຍແທ້ 150g ໜານຸ່ມ ໃສ່ສະບາຍ ບໍ່ຮ້ອນ ລະບາຍອາກາດໄດ້ດີເລີດ ດີໄຊນ໌ຊົງຫຼົມຫລ້າສະໄໝ ເໝາະກັບທຸກການແຕ່ງຕົວ.',
    options: 'Size: M, L, XL'
  },
  {
    id: 'p29',
    name: 'ໂສ້ງຢີນແຟຊັ່ນ Retro Denim Jeans Slim Fit',
    price: 195000,
    originalPrice: 280000,
    category: 'fashion',
    brand: 'Levi\'s',
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?q=80&w=600&auto=format&fit=crop',
    badge: 'ຍອດນິຍົມ',
    countSold: 'ຂາຍແລ້ວ 620+ ຊິ້ນ',
    description: 'ໂສ້ງຢີນຂາຍາວຊົງກົງງາມ ຜ້າຢີນໜຽວທົນທານ ໃສ່ແລ້ວຊົງຕົວດີ ເສີມບຸກຄະລິກກະພາບໃຫ້ເບິ່ງດີແບບເທ້ໆ.',
    options: 'Waist Size: 30, 32, 34, 36'
  },
  {
    id: 'p30',
    name: 'ໝາກແກັບກັນແດດ Sports Baseball Cap UNISEX',
    price: 45000,
    originalPrice: 75000,
    category: 'fashion',
    brand: 'Apex',
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?q=80&w=600&auto=format&fit=crop',
    badge: 'ຫຼຸດແຮງ!!',
    countSold: 'ຂາຍແລ້ວ 980+ ຊິ້ນ',
    description: 'ໝວກແກັບກັນແດດ ກັນແສງ UV ໃສ່ໄປທ່ຽວກາງແຈ້ງ ຫຼື ໃສ່ຫຼິ້ນກິລາກໍເທ້ ປັບຂະໜາດສາຍດ້ານຫຼັງໄດ້ສະດວກ.',
    options: 'Color: Navy Blue, All Black, Classic Pink'
  },
  {
    id: 'p31',
    name: 'ສາຍຮັດແອວໜັງແທ້ Men\'s Leather Belt',
    price: 95000,
    originalPrice: 150000,
    category: 'fashion',
    brand: 'VintageLao',
    image: 'https://images.unsplash.com/photo-1624222247344-550fb8ec5519?q=80&w=600&auto=format&fit=crop',
    badge: 'ມາໃໝ່',
    countSold: 'ຂາຍແລ້ວ 290+ ຊິ້ນ',
    description: 'ສາຍຮັດແອວເຮັດຈາກໜັງງົວແທ້ ຄຸນນະພາບສູງ ຫົວເຂັມຂັດໂລຫະສະແຕນເລດປ້ອງກັນສະນິມ ໃສ່ອອກງານຫຼືເຮັດວຽກກໍງາມ.',
    options: 'Length: 115cm, 125cm'
  },
  {
    id: 'p32',
    name: 'ລິບສະຕິກບຳລຸງຮີມສົບ Moisture Lip Balm Aloe',
    price: 25000,
    originalPrice: 45000,
    category: 'cosmetics',
    brand: 'NaturaLao',
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=600&auto=format&fit=crop',
    badge: 'ຄວາມງາມ 💄',
    countSold: 'ຂາຍແລ້ວ 1.8k+ ຊິ້ນ',
    description: 'ລິບບຳລຸງຮີມສົບສະກັດຈາກຫວ້ານຫາງແຂ້ ຫຼຸດຜ່ອນຮີມສົບແຫ້ງແຕກ ແຫ້ງແຕກລອກ ໃຫ້ປາກອົມຊົມພູເປັນທຳມະຊາດຕະຫຼອດວັນ.',
    options: 'Flavor: Aloe Vera, Strawberry Glow'
  },
  {
    id: 'p33',
    name: 'ໂທນເນີບຳລຸງຜິວຊຸ່ມຊື່ນ Hyaluronic Moisture Toner',
    price: 135000,
    originalPrice: 210000,
    category: 'cosmetics',
    brand: 'NaturaLao',
    image: 'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=600&auto=format&fit=crop',
    badge: 'ແນະນຳ',
    countSold: 'ຂາຍແລ້ວ 590+ ຊິ້ນ',
    description: 'ໂທນເນີປັບສະພາບຜິວ ກະຊັບຮູຂຸມຂົນ ຮັກສາລະດັບຄວາມຊຸ່ມຊື່ນໃຫ້ແກ່ຜິວ ກຽມພ້ອມຮັບການບຳລຸງຂັ້ນຕໍ່ໄປ.',
    options: 'Size: 150ml'
  },
  {
    id: 'p34',
    name: 'ຄີມມາກໜ້າຖ່ານໄຜ່ລ້າງສານພິດ Clay Mask Bamboo',
    price: 75000,
    originalPrice: 120000,
    category: 'cosmetics',
    brand: 'NaturaLao',
    image: 'https://images.unsplash.com/photo-1567894192231-d22d9c134940?q=80&w=600&auto=format&fit=crop',
    badge: 'ຫຼຸດພິເສດ 37%',
    countSold: 'ຂາຍແລ້ວ 310+ ຊິ້ນ',
    description: 'ຄີມພອກໜ້າຖ່ານໄຜ່ທຳມະຊາດ ດູດຊຶມສິ່ງເປິເປື້ອນ ແລະ ຄວາມມັນສ່ວນເກີນເທິງໃບໜ້າຢ່າງມີປະສິດທິພາບ ຫຼຸດສິວອຸດຕັນ.',
    options: 'Size: 80g Jar'
  },
  {
    id: 'p35',
    name: 'ລູກກິ້ງບໍລິຫານໜ້າທ້ອງ Double Spring Ab Roller',
    price: 110000,
    originalPrice: 165000,
    category: 'sports',
    brand: 'SportX',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=600&auto=format&fit=crop',
    badge: 'ອຸປະກອນກິລາ',
    countSold: 'ຂາຍແລ້ວ 240+ ຊິ້ນ',
    description: 'ລູກກິ້ງເຝິກກ້າມເນື້ອທ້ອງ ພ້ອມແຜ່ນຮອງຫົວເຂົ່າ ກົນໄກດີດກັບອັດຕະໂນມັດ ປອດໄພ ຊ່ວຍສ້າງ Six-Pack ໄດ້ງ່າຍໆຢູ່ເຮືອນຂອງທ່ານ.',
    options: 'Color: Speed Black'
  },
  {
    id: 'p36',
    name: 'ຊຸດສາຍຢາງຍືດອອກກຳລັງກາຍ Resistance Bands 5-Levels',
    price: 55000,
    originalPrice: 85000,
    category: 'sports',
    brand: 'SportX',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=600&auto=format&fit=crop',
    badge: 'ຄຸ້ມຄ່າສຸດໆ',
    countSold: 'ຂາຍແລ້ວ 760+ ຊິ້ນ',
    description: 'ຊຸດສາຍຢາງຍືດແຮງຕ້ານ 5 ລະດັບຄວາມໜັກໜ່ວງ ເໝາະສຳລັບໂຢຄະ, ຟິດເນສ, ສ້າງກ້າມເນື້ອແຂນ ແລະ ຂາ.',
    options: 'Set: 5 resistance levels'
  },
  {
    id: 'p37',
    name: 'ກະຕິກນ້ຳກິລາ Sports Water Bottle Sweatproof 1L',
    price: 60000,
    originalPrice: 95000,
    category: 'sports',
    brand: 'Apex',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?q=80&w=600&auto=format&fit=crop',
    badge: 'ຫຼຸດພິເສດ',
    countSold: 'ຂາຍແລ້ວ 490+ ຊິ້ນ',
    description: 'ກະຕິກນ້ຳກິລາກັນຮົ່ວ ຄວາມຈຸ 1 ລິດ ປອດສານ BPA ມີຫູຫິ້ວພົກພາງ່າຍ ເໝາະກັບການໄປຟິດເນດ ແລະ ແລ່ນກາງແຈ້ງ.',
    options: 'Color: Space Gray, Neon Yellow'
  },
  {
    id: 'p38',
    name: 'ເຊັດກົບຢາງທັອບໂປຼ 5 ໂຕພ້ອມກ່ອງ Top-Lure Rubber Frogs Set',
    price: 75000,
    originalPrice: 110000,
    category: 'sports',
    brand: 'LurePro',
    image: 'https://images.unsplash.com/photo-1605647540924-852290f6b0d5?q=80&w=600&auto=format&fit=crop',
    badge: 'ກົບຢາງຍອດນິຍົມ 🐸',
    countSold: 'ຂາຍແລ້ວ 550+ ຊິ້ນ',
    description: 'ຊຸດກົບຢາງຕົກປາຂະໜາດນ້ອຍ 5 ໂຕ 5 ສີ ຄົບທຸກແອັກຊັ້ນ ມີໃບຫລິວສ້າງຄື້ນ ພ້ອມກ່ອງເກັບສຽບເຫຍື້ອພົກພາ ສາມາດຕົກປາຊອນໄດ້ດີເລີດ.',
    options: 'Set: 5 Lures + Combat Box'
  }
];

export const PROMO_BANNER = {
  title: 'ຫຼຸດແຮງທ້າຍປີ!! ສູງສຸດ 70%',
  subtitle: 'ສະເຫຼີມສະຫຼອງປີໃໝ່ລາວດ້ວຍໂປຣໂມຊັ່ນສຸດພິເສດ ແລະ ຂອງແຖມຫຼວງຫຼາຍ',
  image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBZMxcgyuy_Z_9T53pDWe1WVxKblba9VuTMkcCzwB-58MxnBUfhR0YSIv9RTVo6wbl9LW7iSQ0yUQC-_4-RdmSjoYF17BFunL1JFYCB3iTqPlxga1HaODNHJ2V7l3a7df0DxYX_B9tDlAX2KT6zAGd1Bbv1n30t1BM1wwDh-pR1ZF-qB3M8P7oPPc_2k-mHd5cFz95RpMy9agQqkEkSfY9t3zlJ2T7up0L4bau_vG8TZuc0phybE6cdpQEew8_uc7cz7Y06lUWnuWE',
  code: 'LAO2026',
  discountText: 'ຫຼຸດເພີ່ມ 50,000 ກີບ'
};
